#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 7

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#303446"
bspc config focused_border_color "#babbf1"
bspc config urgent_border_color "#e78284"
bspc config preset_border_color "#81c8be"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a scpad sticky=on state=floating rectangle=1550x800+190+150

feh --bg-scale ~/Downloads/04.jpg &
picom --config $HOME/.config/picom/picom.conf &
polybar main &
copyq &
/usr/lib/polkit-kde-authentication-agent-1 &
