#!/bin/sh

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

export PATH="/home/ninjafire/.local/bin:/sbin:$PATH"
export PATH=$PATH:/var/lib/flatpak/exports/bin:~/.local/share/flatpak/exports/bin

IFS=:
if stest -dqr -n "$cache" $PATH; then
  stest -flx $PATH | sort -u | tee "$cache"
else
  cat "$cache"
fi
